### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by licengkuri** [LongSoft/PFSExtractor#1]
please update for new bios scrip.because this version not wok.Thanks

**Comment by NikolajSchlej** [comment]
This tool is not supported anymore, try [PFSExtractor-RS](https://github.com/LongSoft/PFSExtractor-RS) or [Plutomaniac's extractor from BIOSTools](https://github.com/platomav/BIOSUtilities/tree/master/Dell%20PFS%20BIOS%20Extractor) instead.
